### ISSUE TITLE
[dependency-track] Support for release 4.0.1

### ISSUE THREAD

**Issue by rmkanda** [evryfs/helm-charts#42]
dependency-track has released new major version. Also the architecture is different from from 3.x. Can we add support for 4.x ?

https://docs.dependencytrack.org/changelog/

@davidkarlsen @stevespringett

**Comment by davidkarlsen** [comment]
@rmkanda would you like to do a PR for this?

**Comment by Otterian** [comment]
Support for 4.x is OK as long as one is starting with a fresh installation of DT, but the upgrade path doesn't look ready yet ref the DT changelog for 4.0: The new major version needs a database migration in order to be compatible with the new data model.
There's some WIP on scripts for migrating the database: https://github.com/DependencyTrack/v3.8.0-v4.0.0-migration

It also looks like DT has been moved to a new repo on Docker Hub, where there's a bundled image which I suppose is the relevant image here, but it says "deprecated" in the description, although the most recent update was ~9 hours ago.

**Comment by davidkarlsen** [comment]
Go for the frontend + api variant me thinks.
Let them be individual deployments in the same chart. Both will need ingress (to expose the api and serve the frontend)

**Comment by davidkarlsen** [comment]
@Otterian the front-end issue is fixed now and you can test with the updated image tagged as `snapshot`: https://hub.docker.com/r/dependencytrack/frontend/tags?page=1&ordering=last_updated

**Comment by muteid10t** [comment]
Has there been any progress on getting this working?

**Comment by Otterian** [comment]
@muteid10t I'm hoping to be able to smooth things over this week. Widely depends on the time I have to spare - but I'll try.

**Comment by davidkarlsen** [comment]
Fixed
