### ISSUE TITLE
Dependency-track chart - What should API_BASE_URL Setting be for Apiserver behind a K8s service?

### ISSUE THREAD

**Issue by Homopatrol** [evryfs/helm-charts#62]
**Describe the bug**

I am deploying the helm chart in this repo alongside the [apiserver](https://github.com/DependencyTrack/dependency-track/blob/master/src/main/docker/Dockerfile) and [frontend](https://github.com/DependencyTrack/frontend/blob/master/docker/Dockerfile) which are packaged as separate K8s deployments and services within this.

When we try to login in via the UI and we receive **HTTP 405 Method Not Allowed.**

Given that the chart deploys frontend and backend as separate deployments and services, what should we be using as the API_BASE_URL in the frontend so that it can talk to the backend and we don't receive the HTTP error.

**Version of Helm and Kubernetes**:
Helm v3.5.2
Kubernetes 1.19.0

**Which chart**:
Dependency Track 4.2.0 / Chart 1.0.4

**What happened**:

From the Dependency Track documentation and here https://github.com/DependencyTrack/frontend#deployment that something might need to be provided for API_BASE_URL.

**What you expected to happen**:
We are able to login in via the UI without receiving a HTTP error.

**How to reproduce it** (as minimally and precisely as possible):

- Install Dependency Track with the chart.
- Go to the URL created for Dependency Track.
- Submit initial startup default credentials and login.

**Comment by davidkarlsen** [comment]
that's odd, we run same chart w/o any special setting and it work out of the box. it seems with API_URL="" as today u get the current req

**Comment by namloc2001** [comment]
Hi, I'm working with @Homopatrol . We are running this on OpenShift. I have just performed an install this morning and this is what happens:

1. Because of OpenShift's SCCs, we need to ensure serviceAccounts are created for each deployment and these are added to the `anyuid` SCC. So we will use `--set postgresql.serviceAccount.enabled=true` and prior to deployment, configure:
```
oc adm policy add-scc-to-user anyuid -z dependency-track-frontend
oc adm policy add-scc-to-user anyuid -z dependency-track-apiserver
oc adm policy add-scc-to-user anyuid -z dependency-track-postgresql
```

2. As I don't have a lot of resource in my cluster and the apiserver resource requests are pretty hungry, we only spin up one Frontend server and reduce the apiserver CPU requests to ensure it gets scheduled and starts up:
```
helm install dependency-track evryfs-oss/dependency-track --set postgresql.serviceAccount.enabled=true --set frontend.replicaCount=1 --set apiserver.resources.requests.cpu="200m"
```

3. This means we then see:
```
oc get pod
NAME                                         READY     STATUS         RESTARTS   AGE
dependency-track-apiserver-bc5fc9db5-c7dbw   1/1       Running        0          76s
dependency-track-frontend-5df569544f-2zd26   1/1       Running        0          7m11s
dependency-track-postgresql-0                1/1       Running        0          6m30s
```

4. I then create a route to the frontend service:
```
oc create route edge --service=dependency-track-frontend --hostname=dtracknew.<my.domain.com>
```

5. I access the UI and enter the admin/admin username and password and click on "Login". I then get the following pop up on the screen:
![image](https://user-images.githubusercontent.com/30868661/112608842-b6102900-8e12-11eb-8d24-bf1a676b827b.png)

6. I check logs on frontend pod and see the `405` is logged:
```
172.30.224.5 - - [26/Mar/2021:08:59:35 +0000] "POST /api/v1/user/login HTTP/1.1" 405 157 "https://dtracknew.<my.domain.com>/login?redirect=%2Fdashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0" "10.112.78.7"
```

So I can see from the log it is attempting to POST to the login api (`POST /api/v1/user/login HTTP/1.1`) but I can't see any reference to the Backend URL (which I presume has to be the apiserver service URL) and I haven't entered any information that would let it know what the Backend is called.

**Comment by namloc2001** [comment]
Right, so after staring at this for many hours, I think I understand it and have managed to resolve it within our environment.

I'm afraid I have to disagree with your statement @davidkarlsen 

> that's odd, we run same chart w/o any special setting and it work out of the box. it seems with API_URL="" as today u get the current req url

Because the default setting for the helm chart, regarding Ingress, is that is is disabled, as per [this setting](https://github.com/evryfs/helm-charts/blob/master/charts/dependency-track/values.yaml#L125) and this ["if" statement](https://github.com/evryfs/helm-charts/blob/master/charts/dependency-track/templates/ingress.yaml#L1). Therefore installing with the command in the [README](https://github.com/evryfs/helm-charts/blob/master/charts/dependency-track/README.md), won't work out the box:
```
helm install dependency-track evryfs-oss/dependency-track --namespace dependency-track
```

Instead the `ingress.enabled` settings in [values.yaml](https://github.com/evryfs/helm-charts/blob/master/charts/dependency-track/values.yaml#L125) either needs to be set to `true` or the installation command be updated to be `helm install dependency-track evryfs-oss/dependency-track --set ingress.enabled=true --namespace dependency-track`.

By using the same ingress for both frontend and apiserver, I presume (as we don't want that setup, which I'll explain in a minute, so I haven't tested it) the API_BASE_URL being blank works fine because it does a POST to the API path at itself.

For us this we will be using a slightly different setup as we do not wish to expose any tool interfaces to the Internet unless absolutely required. So we set [API_BASE_URL](https://github.com/evryfs/helm-charts/blob/master/charts/dependency-track/values.yaml#L30) to be `http://127.0.0.1:8081`. Then we install with the command I shared earlier, without exposing the tool via an ingress (or in OpenShift, a route):
```
cd <to_dir_of_local_chart_copy>
helm install dependency-track --set postgresql.serviceAccount.enabled=true --set frontend.replicaCount=1 --set apiserver.resources.requests.cpu="200m" ./
```
And then we use port-forwarding, running these two commands in parallel:
```
oc port-forward svc/<release-name>-frontend 8080:80
oc port-forward svc/<release-name>-apiserver 8081:80
```

We can then browse to 127.0.0.1:8080 to access the UI and it communicates with the apiserver on tcp/8081 via our tunnel.

**Comment by davidkarlsen** [comment]
ah, yes, w/o ingress you need to configure it. Normally one would run with ingress (and then this is taken care of).
You can control the value through frontend.env, which is a map of name/values: https://github.com/evryfs/helm-charts/blob/master/charts/dependency-track/values.yaml#L28

**Comment by junaid18183** [comment]
> Hi, I'm working with @Homopatrol . We are running this on OpenShift. I have just performed an install this morning and this is what happens:
> 
> 1. Because of OpenShift's SCCs, we need to ensure serviceAccounts are created for each deployment and these are added to the `anyuid` SCC. So we will use `--set postgresql.serviceAccount.enabled=true` and prior to deployment, configure:
> 
> ```
> oc adm policy add-scc-to-user anyuid -z dependency-track-frontend
> oc adm policy add-scc-to-user anyuid -z dependency-track-apiserver
> oc adm policy add-scc-to-user anyuid -z dependency-track-postgresql
> ```
> 
> 2. As I don't have a lot of resource in my cluster and the apiserver resource requests are pretty hungry, we only spin up one Frontend server and reduce the apiserver CPU requests to ensure it gets scheduled and starts up:
> 
> ```
> helm install dependency-track evryfs-oss/dependency-track --set postgresql.serviceAccount.enabled=true --set frontend.replicaCount=1 --set apiserver.resources.requests.cpu="200m"
> ```
> 
> 3. This means we then see:
> 
> ```
> oc get pod
> NAME                                         READY     STATUS         RESTARTS   AGE
> dependency-track-apiserver-bc5fc9db5-c7dbw   1/1       Running        0          76s
> dependency-track-frontend-5df569544f-2zd26   1/1       Running        0          7m11s
> dependency-track-postgresql-0                1/1       Running        0          6m30s
> ```
> 
> 4. I then create a route to the frontend service:
> 
> ```
> oc create route edge --service=dependency-track-frontend --hostname=dtracknew.<my.domain.com>
> ```
> 
> 5. I access the UI and enter the admin/admin username and password and click on "Login". I then get the following pop up on the screen:
>    ![image](https://user-images.githubusercontent.com/30868661/112608842-b6102900-8e12-11eb-8d24-bf1a676b827b.png)
> 6. I check logs on frontend pod and see the `405` is logged:
> 
> ```
> 172.30.224.5 - - [26/Mar/2021:08:59:35 +0000] "POST /api/v1/user/login HTTP/1.1" 405 157 "https://dtracknew.<my.domain.com>/login?redirect=%2Fdashboard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0" "10.112.78.7"
> ```
> 
> So I can see from the log it is attempting to POST to the login api (`POST /api/v1/user/login HTTP/1.1`) but I can't see any reference to the Backend URL (which I presume has to be the apiserver service URL) and I haven't entered any information that would let it know what the Backend is called.

Thanks for the comment, it really saved my day
